run:
	PYTHONPATH=.. python day_05_p1.py
	PYTHONPATH=.. python day_05_p2.py

run-p1:
	PYTHONPATH=.. python day_05_p1.py

run-p2:
	PYTHONPATH=.. python day_05_p2.py

submit-p1:
	PYTHONPATH=.. python day_05_p1.py | xargs aoc submit-answer --part 1

submit-p2:
	PYTHONPATH=.. python day_05_p2.py | xargs aoc submit-answer --part 2